name: Deploy Nuget packages

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '6.0'
  PACKAGE_VERSION: "1.1.${{ github.run_number }}"

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
          dotnet restore Firepuma.Email.Abstractions
          dotnet restore Firepuma.Email.Client
          dotnet restore Firepuma.Email.FunctionApp
          dotnet restore Firepuma.Email.Tests

      - name: Test
        run: dotnet test --no-restore

      - name: Package
        run: |
          dotnet pack --configuration Release --output . -p:PackageVersion=${{ env.PACKAGE_VERSION }} Firepuma.Email.Abstractions/Firepuma.Email.Abstractions.csproj
          dotnet pack --configuration Release --output . -p:PackageVersion=${{ env.PACKAGE_VERSION }} Firepuma.Email.Client/Firepuma.Email.Client.csproj

      - name: Publish
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
